apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubernaris-frontend
  labels:
    app: rubernaris-frontend
    project: rubernaris
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rubernaris-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rubernaris-frontend
    spec:
      containers:
        - name: frontend
          image: cr.rubernaris.team/rubernaris-team-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources: {}
      imagePullSecrets:
        - name: hub-rubernaris-team-pull-secret
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""