apiVersion: v1
kind: Service
metadata:
  name: rubernaris-frontend
  namespace: default
  labels:
    app: rubernaris-frontend
spec:
  selector:
    app: rubernaris-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
